version: '3'
networks:
  loki:
    driver: bridge
volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  jenkins:
    image: jenkins/jenkins
    user: root
    container_name: my_jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/lib/docker/volumes/jenkins_volume/_data:/var/jenkins_home
      - /root/.ssh:/root/.ssh
    restart: always

  db:
    image: postgres
    restart: always
    user: root
    environment:
      POSTGRES_USER: erbol
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tg_bot
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    #ports: #----------- open port only if pg admin is needed, and then close it
    #  - "5433:5432"
    networks:
      - loki

  nginx:
    image: nginx
    user: root
    ports:
      - "80:80"
    volumes:
      - /root/my_telebot/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/my_telebot/html:/html
    restart: always
    depends_on: 
      - backend
    networks:
      - loki

  backend:
    build: ./backend
    container_name: my_backend
    ports:
      - "8000:8000"
    networks:
      - loki

  tg_bot:
    build: ./tg_bot
    volumes:
      - /root/my_telebot/tg_bot:/tg_bot
      - /root/my_telebot/tg_bot/.env:/tg_bot/.env
    restart: always
    networks:
      - loki

  promtail:
    image: grafana/promtail
    volumes:
      - /var/log:/var/log
      - /root/my_telebot/promtail:/etc/promtail
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki

  loki:
    image: grafana/loki
    volumes:
      - /root/my_telebot/loki:/etc/loki
      - /root/my_telebot/volumes/loki:/loki
    ports: 
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana
    user: root
    volumes:
      - /root/my_telebot/loki/grafana/provisioning/:/etc/grafana/provisioning/
      - /root/my_telebot/volumes/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped 
    networks:
      - loki

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - loki
    labels:
      org.label-schema.group: "monitoring"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - /root/my_telebot/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - loki

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0 #gcr.io/google-containers/cadvisor:v0.34.0
    privileged: true
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      # - /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - loki
    labels:
      org.label-schema.group: "monitoring"