version: '3'
# docker-compose -f docker-compose.yml build 
# docker-compose -f docker-compose.yml up -d
services:
  tg_request:
    build: ./tg_request
    user: root
    container_name: my_tg_request
    depends_on:
      - backend
  jenkins:
    image: jenkins/jenkins
    user: root
    container_name: my_jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/lib/docker/volumes/jenkins_volume/_data:/var/jenkins_home
    restart: always
  db:
    image: postgres
    restart: always
    user: root
    environment:
      POSTGRES_USER: erbol
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tg_bot
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  nginx:
    image: nginx
    user: root
    ports:
      - "80:80"
    volumes:
      - /root/my_telebot/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - tg_request
  backend:
    build: ./backend
    container_name: my_backend
    ports:
      - "8000:8000"