version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    user: root
    container_name: my_jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/lib/docker/volumes/jenkins_volume/_data:/var/jenkins_home
      - /root/.ssh:/var/jenkins_home/.ssh
    restart: always
  db:
    image: postgres
    restart: always
    user: root
    environment:
      POSTGRES_USER: erbol
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tg-bot
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
