version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/lib/docker/volumes/jenkins_volume/_data:/var/jenkins_home
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: erbol
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tg-bot
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
