version: '3'
# docker-compose -f docker-compose.yml build 
# docker-compose -f docker-compose.yml up -d
services:
  jenkins:
    image: jenkins/jenkins
    user: root
    container_name: my_jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/lib/docker/volumes/jenkins_volume/_data:/var/jenkins_home
    restart: always
  db:
    image: postgres
    restart: always
    user: root
    environment:
      POSTGRES_USER: erbol
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tg_bot
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  nginx:
    image: nginx
    user: root
    ports:
      - "80:80"
    volumes:
      - /root/my_telebot/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on: 
      - backend
  backend:
    build: ./backend
    container_name: my_backend
    ports:
      - "8000:8000"
  tg_bot:
    build: ./tg_bot
    volumes:
      - /root/my_telebot/tg_bot:/tg_bot
      - /root/my_telebot/tg_bot/.env:/tg_bot/.env
#    restart: always