version: '3'
# docker-compose -f docker-compose.yml build 
# docker-compose -f docker-compose.yml up -d
services:
  app:
    build: /root/my_telebot/app
    container_name: my_flask
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes: 
      - /root/my_telebot/app:/app
    expose: 
      - 5000
    restart: always
  jenkins:
    image: jenkins/jenkins
    user: root
    container_name: my_jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/lib/docker/volumes/jenkins_volume/_data:/var/jenkins_home
      - /root/.ssh:/var/jenkins_home/.ssh
    restart: always
  db:
    image: postgres
    restart: always
    user: root
    environment:
      POSTGRES_USER: erbol
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tg-bot
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  ngnx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/html:/usr/share/nginx/html
