global:
  scrape_interval: 15s


scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginx:80']
        labels:
          path: /nginx_status