global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'loki'
    scrape_interval: 5s
    static_configs:
      - targets: ['loki:3100']
