
apiVersion: 1

query_range:
  split_queries_by_interval: 24h

frontend:
  max_outstanding_per_tenant: 1024


datasources:
  - name: Loki
    type: loki
    url: http://loki:3100
    isDefault: true
    
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    editable: true
      
  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    jsonData:
      implementation: 'prometheus'
    basicAuth: false
    basicAuthUser: 
    basicAuthPassword: 